main_file: "48Presets.pd"

midi_controllers:

 Master_Volume:
  midi_cc: 7
  value: 88
 Preset:
  midi_cc: 114
  value: 1
 Morph Speed:
  midi_cc: 60
  value: 40
 LFO Speed Osc3: 
  midi_cc: 28
  value: 40

 Select Seq:
  midi_cc: 18
  value: 47
 Seq Tempo:
  midi_cc: 19 
  value: 107
 Random Seq:
  midi_cc: 20
  value: 0
 Seq Transpose :
  midi_cc: 21
  value: 107
  
 Oscillator 1:
  midi_cc: 77
  value: 41
 Oscillator 2:
  midi_cc: 17
  value: 41
 Oscillator 3:
  midi_cc: 93
  value: 41
 Sequencer Level:
  midi_cc: 91
  value: 70
  
 Attack:
  midi_cc: 73
  value: 37
 Decay:
  midi_cc: 75
  value: 5
 Sustain:
  midi_cc: 79
  value: 47
 Release:
  midi_cc: 72
  value: 123
  
 Filter Cutoff Osc3:
  midi_cc: 74
  value: 36
 Filter Res Osc3:
  midi_cc: 71
  value: 82
 VCA Level:
  midi_cc: 76
  value: 0
 VCA Env Level:
  midi_cc: 16
  value: 107
  
 Delay Rate Left:
  midi_cc: 50
  value: 70
 Delay Rate Right:
  midi_cc: 51
  value: 82
 Delay Feedback:
  midi_cc: 52
  value: 70
 Delay Dry/Wet:
  midi_cc: 53
  value: 107
  
 Delay Lowpass:
  midi_cc: 54
  value: 70
 
  
  
  
  
